import React, { useEffect, useState } from 'react';
import { SafeAreaView, View, Text, TextInput, Pressable, FlatList, StyleSheet, Alert } from 'react-native';
import * as SecureStore from 'expo-secure-store';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { Audio } from 'expo-av';

type Room = { id: string; title: string; category: string; viewerCount: number; creator?: { displayName: string; username: string } };
const API = process.env.EXPO_PUBLIC_API_URL ?? 'http://localhost:4000';
async function api<T>(path: string, options: RequestInit = {}): Promise<T> { const uid = await SecureStore.getItemAsync('firebase_uid'); const r = await fetch(`${API}${path}`, { ...options, headers: { 'content-type': 'application/json', ...(uid ? { 'x-firebase-uid': uid } : {}), ...(options.headers ?? {}) } }); if (!r.ok) throw new Error((await r.json()).error ?? 'Request failed'); return r.json(); }
const copy = { en: { discover: 'Discover', trending: 'Trending live rooms', search: 'Search creators, tags, rooms', goLive: 'Go live', profile: 'Profile', wallet: 'Wallet', viewers: 'viewers' }, si: { discover: 'සොයන්න', trending: 'දැනට ජනප්‍රියයි', search: 'නිර්මාණකරුවන් සොයන්න', goLive: 'සජීවී වන්න', profile: 'පැතිකඩ', wallet: 'පසුම්බිය', viewers: 'නරඹන්නන්' }, ta: { discover: 'கண்டறி', trending: 'பிரபல நேரலைகள்', search: 'படைப்பாளர்களைத் தேடுங்கள்', goLive: 'நேரலை தொடங்கு', profile: 'சுயவிவரம்', wallet: 'பணப்பை', viewers: 'பார்வையாளர்கள்' } };
export default function App() { const [locale, setLocale] = useState<'en'|'si'|'ta'>('en'); const t = copy[locale]; const [rooms, setRooms] = useState<Room[]>([]); const [q, setQ] = useState(''); const [camera, setCamera] = useState(false); const [permission, requestPermission] = useCameraPermissions(); useEffect(() => { api<Room[]>(`/v1/discover?q=${encodeURIComponent(q)}`).then(setRooms).catch(() => setRooms([])); }, [q]); const startLive = async () => { if (!permission?.granted) { const p = await requestPermission(); if (!p.granted) return; } await Audio.requestPermissionsAsync(); setCamera(true); }; if (camera) return <SafeAreaView style={styles.black}><CameraView style={styles.camera} facing="front" /><View style={styles.liveBar}><Text style={styles.liveTitle}>LIVE · 0 viewers</Text><Pressable onPress={() => setCamera(false)} style={styles.stop}><Text style={styles.stopText}>End live</Text></Pressable></View></SafeAreaView>; return <SafeAreaView style={styles.safe}><View style={styles.header}><View><Text style={styles.eyebrow}>LUMALIVE</Text><Text style={styles.title}>{t.discover}</Text></View><View style={styles.localeRow}>{(['en','si','ta'] as const).map(l => <Pressable key={l} onPress={() => setLocale(l)}><Text style={[styles.locale, locale === l && styles.localeActive]}>{l.toUpperCase()}</Text></Pressable>)}</View></View><TextInput value={q} onChangeText={setQ} placeholder={t.search} placeholderTextColor="#7e879f" style={styles.search} /><View style={styles.sectionHead}><Text style={styles.section}>{t.trending}</Text><Text style={styles.see}>See all</Text></View><FlatList data={rooms} keyExtractor={x => x.id} ListEmptyComponent={<Text style={styles.empty}>Connect the API and seed live rooms to populate discovery.</Text>} renderItem={({ item }) => <Pressable style={styles.card}><View style={styles.thumb}><Text style={styles.thumbText}>LIVE</Text></View><View style={styles.cardInfo}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.creator}>@{item.creator?.username ?? 'creator'} · {item.category}</Text><Text style={styles.viewers}>{item.viewerCount.toLocaleString()} {t.viewers}</Text></View></Pressable>} /><View style={styles.bottom}><Pressable style={styles.nav}><Text style={styles.navIcon}>⌂</Text><Text style={styles.navText}>{t.discover}</Text></Pressable><Pressable style={styles.liveButton} onPress={startLive}><Text style={styles.plus}>＋</Text><Text style={styles.liveText}>{t.goLive}</Text></Pressable><Pressable style={styles.nav}><Text style={styles.navIcon}>◉</Text><Text style={styles.navText}>{t.profile}</Text></Pressable><Pressable style={styles.nav}><Text style={styles.navIcon}>◈</Text><Text style={styles.navText}>{t.wallet}</Text></Pressable></View></SafeAreaView>; }
const styles = StyleSheet.create({ safe:{flex:1,backgroundColor:'#0d1020',paddingHorizontal:20}, black:{flex:1,backgroundColor:'#000'}, camera:{flex:1}, header:{paddingTop:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center'}, eyebrow:{fontSize:12,letterSpacing:3,color:'#9ea7c1',fontWeight:'700'}, title:{fontSize:32,color:'#f5f7ff',fontWeight:'800',marginTop:5}, localeRow:{flexDirection:'row',gap:8}, locale:{color:'#7e879f',fontSize:11,fontWeight:'800'},localeActive:{color:'#ffca5f'},search:{backgroundColor:'#191e32',borderRadius:14,padding:15,color:'#f5f7ff',marginTop:22,fontSize:15},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:28,marginBottom:14},section:{color:'#f5f7ff',fontSize:19,fontWeight:'800'},see:{color:'#ffca5f',fontWeight:'700'},card:{flexDirection:'row',backgroundColor:'#151a2d',borderRadius:18,padding:10,marginBottom:12},thumb:{width:112,height:100,borderRadius:13,backgroundColor:'#4d355b',justifyContent:'flex-end',padding:10},thumbText:{color:'#ffca5f',fontWeight:'900',fontSize:12},cardInfo:{padding:10,flex:1},cardTitle:{color:'#fff',fontWeight:'800',fontSize:16},creator:{color:'#9ea7c1',marginTop:8},viewers:{color:'#d4d9e8',marginTop:10,fontSize:12},empty:{color:'#7e879f',lineHeight:22,marginTop:24},bottom:{position:'absolute',bottom:12,left:20,right:20,height:70,backgroundColor:'#171c30',borderRadius:24,flexDirection:'row',alignItems:'center',justifyContent:'space-around'},nav:{alignItems:'center'},navIcon:{fontSize:20,color:'#aab2ca'},navText:{fontSize:10,color:'#aab2ca',marginTop:4},liveButton:{backgroundColor:'#ffca5f',borderRadius:17,paddingHorizontal:16,paddingVertical:9,alignItems:'center'},plus:{fontSize:20,color:'#15182a',lineHeight:20},liveText:{fontWeight:'900',fontSize:10,color:'#15182a'},liveBar:{position:'absolute',left:20,right:20,bottom:30,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},liveTitle:{color:'#fff',fontWeight:'800'},stop:{backgroundColor:'#ef667a',padding:14,borderRadius:12},stopText:{color:'#fff',fontWeight:'800'}});
